// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Content struct {
	Contentid    uuid.UUID   `json:"contentid"`
	Pageid       pgtype.UUID `json:"pageid"`
	ContentType  string      `json:"content_type"`
	ContentValue pgtype.Text `json:"content_value"`
}

type Element struct {
	Elementid    uuid.UUID   `json:"elementid"`
	Pageid       pgtype.UUID `json:"pageid"`
	ElementType  string      `json:"element_type"`
	PositionX    pgtype.Int4 `json:"position_x"`
	PositionY    pgtype.Int4 `json:"position_y"`
	ContentValue pgtype.Text `json:"content_value"`
}

type Page struct {
	Pageid          uuid.UUID        `json:"pageid"`
	Url             string           `json:"url"`
	Title           pgtype.Text      `json:"title"`
	MetaDescription pgtype.Text      `json:"meta_description"`
	MetaKeywords    pgtype.Text      `json:"meta_keywords"`
	LastModified    pgtype.Timestamp `json:"last_modified"`
}
